hostname maddy.local

state_dir /data/state
runtime_dir /data/run

openmetrics tcp://0.0.0.0:9749 { }

target.queue hold_queue {
    target &dead_end
    max_tries 9999
}

msgpipeline dead_end {
    default_destination {
        reject 451 4.3.0 "Message held for inspection"
    }
}

#target.remote outbound {
#    limits {
#        all rate 20 1s
#        all concurrency 10
#    }
#
#    mx_auth {
#        local_policy {
#            min_tls_level none
#            min_mx_level none
#        }
#    }
#}

smtp tcp://0.0.0.0:2525 {
    hostname maddy.local
    tls off
    default_destination {
        deliver_to &hold_queue
    }
}
